### ISSUE TITLE
Gradle Kotlin DSL Support

### ISSUE THREAD

**Issue by invisicat** [Vankka/DependencyDownload#8]
At the moment, there is no support for Gradle Kotlin DSL. It errors out with the error:
```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'dev.vankka.dependencydownload.plugin'.
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:173)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:146)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyLegacyPlugins$2(DefaultPluginRequestApplicator.java:140)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:185)
	... 162 more
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'compileOnly' not found.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:160)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:333)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:150)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:64)
	at dev.vankka.dependencydownload.DependencyDownloadGradlePlugin.apply(DependencyDownloadGradlePlugin.java:32)
	at dev.vankka.dependencydownload.DependencyDownloadGradlePlugin.apply(DependencyDownloadGradlePlugin.java:18)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
```

It would be wonderful if this could be implemented!

**Comment by Vankka** [comment]
I think that error is happening because there is a project that has the DependencyDownload plugin but doesn't have the java plugin, not because of using the Kotlin DSL

**Comment by invisicat** [comment]
This is my `build.gradle.kts` file:
```kotlin
plugins {
    java
    id("io.freefair.lombok") version "6.3.0"
    id("dev.vankka.dependencydownload.plugin") version "1.2.1"
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

group = "network.frostless"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven(url="https://s01.oss.sonatype.org/content/repositories/snapshots/")

    maven(url = "https://nexus.velocitypowered.com/repository/maven-public/")
    maven(url = "https://jitpack.io")

    maven(url="https://mvn-repo.arim.space/affero-gpl3/")
    maven(url="https://mvn-repo.arim.space/gpl3")
    maven(url="https://mvn-repo.arim.space/lesser-gpl3")
}

dependencies {
    // Velocity Dependencies
    compileOnly("com.velocitypowered:velocity-api:3.0.1")
    annotationProcessor("com.velocitypowered:velocity-api:3.0.1")

    compileOnly("org.apache.logging.log4j:log4j-api:2.17.2")


    // LAMP
    implementation("com.github.Revxrsal.Lamp:common:3.0.2")
    implementation("com.github.Revxrsal.Lamp:velocity:3.0.2")

    // Minimessage
    implementation("net.kyori:adventure-text-minimessage:4.10.1")

    implementation("network.frostless:frostcore:0.0.1")
    implementation("network.frostless:ServerAPI:1.0-SNAPSHOT")

    implementation("org.spongepowered:configurate-yaml:4.1.2")
    implementation("io.lettuce:lettuce-core:6.1.8.RELEASE")

    // LibertyBans
    compileOnly("space.arim.libertybans:bans-api:1.0.1")

    implementation("dev.vankka:dependencydownload-runtime:1.2.1")

    compileOnly(fileTree(mapOf("dir" to "extern", "include" to listOf("*.jar"))))
}

tasks {
    shadowJar {
        minimize {
            enabled = true
        //    exclude(dependency("org.postgresql:postgresql:42.3.3"))
        }
       // relocate("org.postgresql:postgresql:*", "network.frostless.shaded.postgresql")
        archiveFileName.set("${project.rootProject.name}-${project.name}-v${project.version}.jar")
        destinationDirectory.set(file("$rootDir/output"))
    }
}
```

The java plugin is instantiated at the top there.

**Comment by invisicat** [comment]
I've fixed the Gradle build issue by adding this
```kotlin
buildscript {
    repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
    dependencies {
        classpath("dev.vankka:gradle-plugin:1.2.1")
    }
}

apply(plugin = "dev.vankka.dependencydownload.plugin")
```

Though now I cannot access `runtimeDownload` nor `runtimeDownloadOnly` in the dependencies block. Though I can see `generateRuntimeDownloadResourceForRuntimeDownload` and `generateRuntimeDownloadResourceForRuntimeDownloadOnly` in my build tasks.

**Comment by Vankka** [comment]
> This is my `build.gradle.kts` file:
> 
> ```kotlin
> plugins {
>     java
>     id("io.freefair.lombok") version "6.3.0"
>     id("dev.vankka.dependencydownload.plugin") version "1.2.1"
>     id("com.github.johnrengelman.shadow") version "7.1.2"
> }
> 
> group = "network.frostless"
> version = "1.0-SNAPSHOT"
> 
> repositories {
>     mavenCentral()
>     maven(url="https://s01.oss.sonatype.org/content/repositories/snapshots/")
> 
>     maven(url = "https://nexus.velocitypowered.com/repository/maven-public/")
>     maven(url = "https://jitpack.io")
> 
>     maven(url="https://mvn-repo.arim.space/affero-gpl3/")
>     maven(url="https://mvn-repo.arim.space/gpl3")
>     maven(url="https://mvn-repo.arim.space/lesser-gpl3")
> }
> 
> dependencies {
>     // Velocity Dependencies
>     compileOnly("com.velocitypowered:velocity-api:3.0.1")
>     annotationProcessor("com.velocitypowered:velocity-api:3.0.1")
> 
>     compileOnly("org.apache.logging.log4j:log4j-api:2.17.2")
> 
> 
>     // LAMP
>     implementation("com.github.Revxrsal.Lamp:common:3.0.2")
>     implementation("com.github.Revxrsal.Lamp:velocity:3.0.2")
> 
>     // Minimessage
>     implementation("net.kyori:adventure-text-minimessage:4.10.1")
> 
>     implementation("network.frostless:frostcore:0.0.1")
>     implementation("network.frostless:ServerAPI:1.0-SNAPSHOT")
> 
>     implementation("org.spongepowered:configurate-yaml:4.1.2")
>     implementation("io.lettuce:lettuce-core:6.1.8.RELEASE")
> 
>     // LibertyBans
>     compileOnly("space.arim.libertybans:bans-api:1.0.1")
> 
>     implementation("dev.vankka:dependencydownload-runtime:1.2.1")
> 
>     compileOnly(fileTree(mapOf("dir" to "extern", "include" to listOf("*.jar"))))
> }
> 
> tasks {
>     shadowJar {
>         minimize {
>             enabled = true
>         //    exclude(dependency("org.postgresql:postgresql:42.3.3"))
>         }
>        // relocate("org.postgresql:postgresql:*", "network.frostless.shaded.postgresql")
>         archiveFileName.set("${project.rootProject.name}-${project.name}-v${project.version}.jar")
>         destinationDirectory.set(file("$rootDir/output"))
>     }
> }
> ```
> 
> The java plugin is instantiated at the top there.

I was able to use the `runtimeDownload` and `runtimeDownloadOnly` configurations, build (*after removing dependencies that did not resolve) and run the resource generation task(s) with this build script, Gradle 7.4 with Java 8, 11 & 17

**Comment by invisicat** [comment]
Yup, found that the issue was that I was using **Gradle 7.2**, once I updated to **Gradle 7.4.2** it works. Thank you for making this!
